# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: 'pdesaidocker/easy-kart-ui'
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'docker-service-connection'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
    - job: BuildAngular
      displayName: 'Build and Push Docker Image'    
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Install Node.js'

      - script: |
          npm install -g @angular/cli
          npm install
          ng build --configuration=production
        displayName: 'npm install and build'
      - task: Docker@2
        displayName: Build and push Docker image
        inputs:
          command: 'buildAndPush'
          repository: $(imageRepository)
          dockerfile: 'dockerfile'
          buildContext: '.'
          tags: $(tag)
          containerRegistry: $(dockerRegistryServiceConnection)
- stage: Deploy
  displayName: DevDeploy
  dependsOn: Build
  jobs:
  - job: DeployToAKS
    displayName: Deploy to AKS
    steps:
    - script: |
        echo "Replacing {{imageTag}} in deployment.yaml with $(tag)"
        sed -i 's/{{imageTag}}/$(tag)/g' deployment.yaml
      displayName: Replace tag in deployment.yaml
    - task: Kubernetes@1
      displayName: Apply deployment.yaml
      inputs:
        kubernetesServiceEndpoint: 'aks-service-conn'
        namespace: 'easy-kart'
        command: 'apply'
        arguments: '-f deployment.yaml'
    - task: Kubernetes@1
      displayName: Apply service.yaml
      inputs:
        kubernetesServiceEndpoint: 'aks-service-conn'
        namespace: 'easy-kart'
        command: 'apply'
        arguments: '-f service.yaml' 
